Data From Weeks 5 & 6 Datasets was used(BOING-BOING-CANDY-HIERARCHY-2016-SURVEY-Response)

Import all the needed libraries

In [78]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [79]:
data = pd.read_excel("C:/Users/pro_v/Desktop/BOING-BOING-CANDY-HIERARCHY-2016-SURVEY-Responses.xlsx")

In [80]:
data.head()

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN

Chapter 7. 
Filter out missing data

In [81]:
for c in data.columns:
    miss = data[c].isnull().sum()
    if miss>0:
        print("{} has {} missing value(s)".format(c,miss))
    else:
        print("{} has NO missing value!".format(c))

Timestamp has NO missing value!
Are you going actually going trick or treating yourself? has NO missing value!
Your gender: has 9 missing value(s)
How old are you? has 33 missing value(s)
Which country do you live in? has 21 missing value(s)
Which state, province, county do you live in? has 79 missing value(s)
 [100 Grand Bar] has 78 missing value(s)
 [Anonymous brown globs that come in black and orange wrappers] has 26 missing value(s)
 [Any full-sized candy bar] has 17 missing value(s)
 [Black Jacks] has 203 missing value(s)
 [Bonkers (the candy)] has 221 missing value(s)
 [Bonkers (the board game)] has 232 missing value(s)
 [Bottle Caps] has 79 missing value(s)
 [Box'o'Raisins] has 29 missing value(s)
 [Broken glow stick] has 33 missing value(s)
 [Butterfinger] has 23 missing value(s)
 [Cadbury Creme Eggs] has 21 missing value(s)
 [Candy Corn] has 17 missing value(s)
 [Candy that is clearly just the stuff given out for free at restaurants] has 28 missing value(s)
 [Caramellos] has 79 missing value(s)
 [Cash, or other forms of legal tender] has 22 missing value(s)
 [Chardonnay] has 57 missing value(s)
 [Chick-o-Sticks (we don’t know what that is)] has 211 missing value(s)
 [Chiclets] has 53 missing value(s)
 [Coffee Crisp] has 146 missing value(s)
 [Creepy Religious comics/Chick Tracts] has 46 missing value(s)
 [Dental paraphenalia] has 32 missing value(s)
 [Dots] has 62 missing value(s)
 [Dove Bars] has 45 missing value(s)
 [Fuzzy Peaches] has 122 missing value(s)
 [Generic Brand Acetaminophen] has 68 missing value(s)
 [Glow sticks] has 36 missing value(s)
 [Goo Goo Clusters] has 176 missing value(s)
 [Good N' Plenty] has 77 missing value(s)
 [Gum from baseball cards] has 46 missing value(s)
 [Gummy Bears straight up] has 35 missing value(s)
 [Hard Candy] has 31 missing value(s)
 [Healthy Fruit] has 34 missing value(s)
 [Heath Bar] has 54 missing value(s)
 [Hershey's Dark Chocolate] has 24 missing value(s)
 [Hershey’s Milk Chocolate] has 18 missing value(s)
 [Hershey's Kisses] has 20 missing value(s)
 [Hugs (actual physical hugs)] has 37 missing value(s)
 [Jolly Rancher (bad flavor)] has 33 missing value(s)
 [Jolly Ranchers (good flavor)] has 34 missing value(s)
 [JoyJoy (Mit Iodine!)] has 243 missing value(s)
 [Junior Mints] has 41 missing value(s)
 [Senior Mints] has 212 missing value(s)
 [Kale smoothie] has 76 missing value(s)
 [Kinder Happy Hippo] has 215 missing value(s)
 [Kit Kat] has 22 missing value(s)
 [LaffyTaffy] has 59 missing value(s)
 [LemonHeads] has 80 missing value(s)
 [Licorice (not black)] has 31 missing value(s)
 [Licorice (yes black)] has 28 missing value(s)
 [Lindt Truffle] has 51 missing value(s)
 [Lollipops] has 37 missing value(s)
 [Mars] has 50 missing value(s)
 [Mary Janes] has 194 missing value(s)
 [Maynards] has 262 missing value(s)
 [Mike and Ike] has 65 missing value(s)
 [Milk Duds] has 50 missing value(s)
 [Milky Way] has 32 missing value(s)
 [Regular M&Ms] has 27 missing value(s)
 [Peanut M&M’s] has 25 missing value(s)
 [Blue M&M's] has 65 missing value(s)
 [Red M&M's] has 63 missing value(s)
 [Third Party M&M's] has 72 missing value(s)
 [Minibags of chips] has 43 missing value(s)
 [Mint Kisses] has 72 missing value(s)
 [Mint Juleps] has 134 missing value(s)
 [Mr. Goodbar] has 82 missing value(s)
 [Necco Wafers] has 79 missing value(s)
 [Nerds] has 48 missing value(s)
 [Nestle Crunch] has 41 missing value(s)
 [Now'n'Laters] has 129 missing value(s)
 [Peeps] has 59 missing value(s)
 [Pencils] has 52 missing value(s)
 [Person of Interest Season 3 DVD Box Set (not including Disc 4 with hilarious outtakes)] has 123 missing value(s)
 [Pixy Stix] has 56 missing value(s)
 [Reese’s Peanut Butter Cups] has 27 missing value(s)
 [Reese's Pieces] has 29 missing value(s)
 [Reggie Jackson Bar] has 246 missing value(s)
 [Rolos] has 47 missing value(s)
 [Skittles] has 33 missing value(s)
 [Smarties (American)] has 47 missing value(s)
 [Smarties (Commonwealth)] has 163 missing value(s)
 [Snickers] has 36 missing value(s)
 [Sourpatch Kids (i.e. abominations of nature)] has 62 missing value(s)
 [Spotted Dick] has 177 missing value(s)
 [Starburst] has 39 missing value(s)
 [Sweet Tarts] has 41 missing value(s)
 [Swedish Fish] has 56 missing value(s)
 [Sweetums (a friend to diabetes)] has 261 missing value(s)
 [Tic Tacs] has 42 missing value(s)
 [Those odd marshmallow circus peanut things] has 70 missing value(s)
 [Three Musketeers] has 45 missing value(s)
 [Tolberone something or other] has 37 missing value(s)
 [Trail Mix] has 48 missing value(s)
 [Twix] has 35 missing value(s)
 [Vials of pure high fructose corn syrup, for main-lining into your vein] has 115 missing value(s)
 [Vicodin] has 94 missing value(s)
 [Whatchamacallit Bars] has 131 missing value(s)
 [White Bread] has 78 missing value(s)
 [Whole Wheat anything] has 76 missing value(s)
 [York Peppermint Patties] has 52 missing value(s)
Please list any items not included above that give you JOY. has 578 missing value(s)
Please list any items not included above that give you DESPAIR. has 701 missing value(s)
Please leave any witty, snarky or thoughtful remarks or comments regarding your choices. has 917 missing value(s)
Guess the number of mints in my hand. has 68 missing value(s)
Betty or Veronica? has 39 missing value(s)
"That dress* that went viral a few years back - when I first saw it, it was ________" has 46 missing value(s)
What is your favourite font? has 169 missing value(s)
Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling] has 82 missing value(s)
Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams] has 83 missing value(s)
Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé] has 84 missing value(s)
Please estimate the degree(s) of separation you have from the following celebrities [Bieber] has 84 missing value(s)
Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon] has 80 missing value(s)
Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)] has 85 missing value(s)
Which day do you prefer, Friday or Sunday? has 24 missing value(s)
Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)? has 45 missing value(s)
When you see the above image of the 4 different websites, which one would you most likely check out (please be honest). has 37 missing value(s)
 [York Peppermint Patties] Ignore has 1259 missing value(s)

In [82]:
data1 = data.dropna()

In [83]:
data

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2016-10-29 16:53:52.516,No,Female,52,USA,TX,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
1255,2016-10-30 06:53:54.735,No,Male,33,united states,minnesota,JOY,DESPAIR,JOY,DESPAIR,...,"Actually, that's me.",3 or higher,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Friday,Sinusoidally around the equator,Science: Latest News and Headlines,NaN
1256,2016-10-30 11:06:10.827,No,Male,NaN,NaN,NaN,JOY,MEH,JOY,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Sunday,nne to east to nnw to s to n,Science: Latest News and Headlines,NaN
1257,2016-10-30 16:07:26.539,No,Male,48,canada,BC,NaN,DESPAIR,JOY,DESPAIR,...,1,2,3 or higher,3 or higher,2,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
1258,2016-10-30 17:06:45.660,Yes,Female,44,Us,Nh,JOY,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN

In [84]:
data1

Empty DataFrame
Columns: [Timestamp, Are you going actually going trick or treating yourself?, Your gender:, How old are you?, Which country do you live in?, Which state, province, county do you live in?,  [100 Grand Bar],  [Anonymous brown globs that come in black and orange wrappers],  [Any full-sized candy bar],  [Black Jacks],  [Bonkers (the candy)],  [Bonkers (the board game)],  [Bottle Caps],  [Box'o'Raisins],  [Broken glow stick],  [Butterfinger],  [Cadbury Creme Eggs],  [Candy Corn],  [Candy that is clearly just the stuff given out for free at restaurants],  [Caramellos],  [Cash, or other forms of legal tender],  [Chardonnay],  [Chick-o-Sticks (we don’t know what that is)],  [Chiclets],  [Coffee Crisp],  [Creepy Religious comics/Chick Tracts],  [Dental paraphenalia],  [Dots],  [Dove Bars],  [Fuzzy Peaches],  [Generic Brand Acetaminophen],  [Glow sticks],  [Goo Goo Clusters],  [Good N' Plenty],  [Gum from baseball cards],  [Gummy Bears straight up],  [Hard Candy],  [Healthy Fruit],  [Heath Bar],  [Hershey's Dark Chocolate],  [Hershey’s Milk Chocolate],  [Hershey's Kisses],  [Hugs (actual physical hugs)],  [Jolly Rancher (bad flavor)],  [Jolly Ranchers (good flavor)],  [JoyJoy (Mit Iodine!)],  [Junior Mints],  [Senior Mints],  [Kale smoothie],  [Kinder Happy Hippo],  [Kit Kat],  [LaffyTaffy],  [LemonHeads],  [Licorice (not black)],  [Licorice (yes black)],  [Lindt Truffle],  [Lollipops],  [Mars],  [Mary Janes],  [Maynards],  [Mike and Ike],  [Milk Duds],  [Milky Way],  [Regular M&Ms],  [Peanut M&M’s],  [Blue M&M's],  [Red M&M's],  [Third Party M&M's],  [Minibags of chips],  [Mint Kisses],  [Mint Juleps],  [Mr. Goodbar],  [Necco Wafers],  [Nerds],  [Nestle Crunch],  [Now'n'Laters],  [Peeps],  [Pencils],  [Person of Interest Season 3 DVD Box Set (not including Disc 4 with hilarious outtakes)],  [Pixy Stix],  [Reese’s Peanut Butter Cups],  [Reese's Pieces],  [Reggie Jackson Bar],  [Rolos],  [Skittles],  [Smarties (American)],  [Smarties (Commonwealth)],  [Snickers],  [Sourpatch Kids (i.e. abominations of nature)],  [Spotted Dick],  [Starburst],  [Sweet Tarts],  [Swedish Fish],  [Sweetums (a friend to diabetes)],  [Tic Tacs],  [Those odd marshmallow circus peanut things],  [Three Musketeers],  [Tolberone something or other],  [Trail Mix],  [Twix], ...]
Index: []

[0 rows x 123 columns]

In [85]:
dat2 = data.dropna(how='all')
dat2

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2016-10-29 16:53:52.516,No,Female,52,USA,TX,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
1255,2016-10-30 06:53:54.735,No,Male,33,united states,minnesota,JOY,DESPAIR,JOY,DESPAIR,...,"Actually, that's me.",3 or higher,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Friday,Sinusoidally around the equator,Science: Latest News and Headlines,NaN
1256,2016-10-30 11:06:10.827,No,Male,NaN,NaN,NaN,JOY,MEH,JOY,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Sunday,nne to east to nnw to s to n,Science: Latest News and Headlines,NaN
1257,2016-10-30 16:07:26.539,No,Male,48,canada,BC,NaN,DESPAIR,JOY,DESPAIR,...,1,2,3 or higher,3 or higher,2,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
1258,2016-10-30 17:06:45.660,Yes,Female,44,Us,Nh,JOY,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN

Fill in missing data

In [86]:
gender = data[["Your gender:"]]

In [87]:
gender1 = gender.dropna()

In [88]:
gender1

     Your gender:
0            Male
1            Male
2          Female
3            Male
4            Male
...           ...
1254       Female
1255         Male
1256         Male
1257         Male
1258       Female

[1250 rows x 1 columns]

Fill in missing data

Fill in missing data. 
Replace values

In [89]:
age = data[["How old are you?"]]

In [90]:
age1 = age.fillna(age.mean())

In [91]:
age1

     How old are you?
0                  22
1                  45
2                  48
3                  57
4                  42
...               ...
1254               52
1255               33
1256              NaN
1257               48
1258               44

[1259 rows x 1 columns]

In [92]:
age.replace(np.nan,50)

     How old are you?
0                  22
1                  45
2                  48
3                  57
4                  42
...               ...
1254               52
1255               33
1256               50
1257               48
1258               44

[1259 rows x 1 columns]

Remove duplicates

In [93]:
age.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1254     True
1255     True
1256     True
1257     True
1258     True
Length: 1259, dtype: bool

In [94]:
age.drop_duplicates()

                       How old are you?
0                                    22
1                                    45
2                                    48
3                                    57
4                                    42
...                                 ...
1192                            ancient
1193                                142
1194                                  7
1197  Old enough to not Trick or Treat.
1245                        49 11/12ths

[99 rows x 1 columns]

Chapter 8
Create hierarchical index

In [95]:
data

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2016-10-29 16:53:52.516,No,Female,52,USA,TX,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
1255,2016-10-30 06:53:54.735,No,Male,33,united states,minnesota,JOY,DESPAIR,JOY,DESPAIR,...,"Actually, that's me.",3 or higher,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Friday,Sinusoidally around the equator,Science: Latest News and Headlines,NaN
1256,2016-10-30 11:06:10.827,No,Male,NaN,NaN,NaN,JOY,MEH,JOY,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Sunday,nne to east to nnw to s to n,Science: Latest News and Headlines,NaN
1257,2016-10-30 16:07:26.539,No,Male,48,canada,BC,NaN,DESPAIR,JOY,DESPAIR,...,1,2,3 or higher,3 or higher,2,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
1258,2016-10-30 17:06:45.660,Yes,Female,44,Us,Nh,JOY,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN

Chapter 8 Combine and Merge Datasets (you will have to either create a new dataset from your existing data or create a relationship between the data I have provided)

In [96]:
df = pd.read_excel("C:/Users/pro_v/Desktop/CANDY-HIERARCHY-2015-SURVEY-Responses.xlsx")
df.head()

,Timestamp,How old are you?,Are you going actually going trick or treating yourself?,[Butterfinger],[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],[Bonkers],[Bottle Caps],...,[Necco Wafers],"Which day do you prefer, Friday or Sunday?",Please estimate the degrees of separation you have from the following folks [Bruce Lee],Please estimate the degrees of separation you have from the following folks [JK Rowling],Please estimate the degrees of separation you have from the following folks [Malala Yousafzai],Please estimate the degrees of separation you have from the following folks [Thom Yorke],Please estimate the degrees of separation you have from the following folks [JJ Abrams],Please estimate the degrees of separation you have from the following folks [Hillary Clinton],Please estimate the degrees of separation you have from the following folks [Donald Trump],Please estimate the degrees of separation you have from the following folks [Beyoncé Knowles]
0,2015-10-23 08:46:20.451,35,No,JOY,NaN,DESPAIR,JOY,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-10-23 08:46:51.583,41,No,JOY,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,...,DESPAIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-10-23 08:47:34.285,33,No,DESPAIR,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,...,DESPAIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-10-23 08:47:58.964,31,No,JOY,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,...,DESPAIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-10-23 08:48:11.719,30,No,NaN,JOY,DESPAIR,JOY,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
df

,Timestamp,How old are you?,Are you going actually going trick or treating yourself?,[Butterfinger],[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],[Bonkers],[Bottle Caps],...,[Necco Wafers],"Which day do you prefer, Friday or Sunday?",Please estimate the degrees of separation you have from the following folks [Bruce Lee],Please estimate the degrees of separation you have from the following folks [JK Rowling],Please estimate the degrees of separation you have from the following folks [Malala Yousafzai],Please estimate the degrees of separation you have from the following folks [Thom Yorke],Please estimate the degrees of separation you have from the following folks [JJ Abrams],Please estimate the degrees of separation you have from the following folks [Hillary Clinton],Please estimate the degrees of separation you have from the following folks [Donald Trump],Please estimate the degrees of separation you have from the following folks [Beyoncé Knowles]
0,2015-10-23 08:46:20.451,35,No,JOY,NaN,DESPAIR,JOY,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-10-23 08:46:51.583,41,No,JOY,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,...,DESPAIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-10-23 08:47:34.285,33,No,DESPAIR,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,...,DESPAIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-10-23 08:47:58.964,31,No,JOY,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,...,DESPAIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-10-23 08:48:11.719,30,No,NaN,JOY,DESPAIR,JOY,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5625,2015-10-31 05:23:40.526,50,No,DESPAIR,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,...,DESPAIR,Friday,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5626,2015-10-31 05:29:26.937,43,No,JOY,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,...,DESPAIR,Sunday,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5627,2015-10-31 06:13:29.083,35,Yes,NaN,JOY,DESPAIR,JOY,NaN,NaN,DESPAIR,...,NaN,Friday,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5628,2015-10-31 06:26:52.566,38,No,JOY,JOY,JOY,JOY,JOY,JOY,JOY,...,JOY,Sunday,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5629,2015-10-31 06:41:31.904,44,No,DESPAIR,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,...,JOY,Friday,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
dfmerge = pd.merge(data,df)
dfmerge

Empty DataFrame
Columns: [Timestamp, Are you going actually going trick or treating yourself?, Your gender:, How old are you?, Which country do you live in?, Which state, province, county do you live in?,  [100 Grand Bar],  [Anonymous brown globs that come in black and orange wrappers],  [Any full-sized candy bar],  [Black Jacks],  [Bonkers (the candy)],  [Bonkers (the board game)],  [Bottle Caps],  [Box'o'Raisins],  [Broken glow stick],  [Butterfinger],  [Cadbury Creme Eggs],  [Candy Corn],  [Candy that is clearly just the stuff given out for free at restaurants],  [Caramellos],  [Cash, or other forms of legal tender],  [Chardonnay],  [Chick-o-Sticks (we don’t know what that is)],  [Chiclets],  [Coffee Crisp],  [Creepy Religious comics/Chick Tracts],  [Dental paraphenalia],  [Dots],  [Dove Bars],  [Fuzzy Peaches],  [Generic Brand Acetaminophen],  [Glow sticks],  [Goo Goo Clusters],  [Good N' Plenty],  [Gum from baseball cards],  [Gummy Bears straight up],  [Hard Candy],  [Healthy Fruit],  [Heath Bar],  [Hershey's Dark Chocolate],  [Hershey’s Milk Chocolate],  [Hershey's Kisses],  [Hugs (actual physical hugs)],  [Jolly Rancher (bad flavor)],  [Jolly Ranchers (good flavor)],  [JoyJoy (Mit Iodine!)],  [Junior Mints],  [Senior Mints],  [Kale smoothie],  [Kinder Happy Hippo],  [Kit Kat],  [LaffyTaffy],  [LemonHeads],  [Licorice (not black)],  [Licorice (yes black)],  [Lindt Truffle],  [Lollipops],  [Mars],  [Mary Janes],  [Maynards],  [Mike and Ike],  [Milk Duds],  [Milky Way],  [Regular M&Ms],  [Peanut M&M’s],  [Blue M&M's],  [Red M&M's],  [Third Party M&M's],  [Minibags of chips],  [Mint Kisses],  [Mint Juleps],  [Mr. Goodbar],  [Necco Wafers],  [Nerds],  [Nestle Crunch],  [Now'n'Laters],  [Peeps],  [Pencils],  [Person of Interest Season 3 DVD Box Set (not including Disc 4 with hilarious outtakes)],  [Pixy Stix],  [Reese’s Peanut Butter Cups],  [Reese's Pieces],  [Reggie Jackson Bar],  [Rolos],  [Skittles],  [Smarties (American)],  [Smarties (Commonwealth)],  [Snickers],  [Sourpatch Kids (i.e. abominations of nature)],  [Spotted Dick],  [Starburst],  [Sweet Tarts],  [Swedish Fish],  [Sweetums (a friend to diabetes)],  [Tic Tacs],  [Those odd marshmallow circus peanut things],  [Three Musketeers],  [Tolberone something or other],  [Trail Mix],  [Twix], ...]
Index: []

[0 rows x 155 columns]

Pivot the data

In [99]:
stacked = df.stack()

In [100]:
stacked

0     Timestamp                                                                                                            2015-10-23 08:46:20.451000
      How old are you?                                                                                                                             35
      Are you going actually going trick or treating yourself?                                                                                     No
       [Butterfinger]                                                                                                                             JOY
       [Anonymous brown globs that come in black and orange wrappers]                                                                         DESPAIR
                                                                                                                                      ...
5629  Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon]                                   3 or higher
      Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)]                   3 or higher
       [Sea-salt flavored stuff, probably chocolate, since this is the "it" flavor of the year]                                               DESPAIR
       [Necco Wafers]                                                                                                                             JOY
      Which day do you prefer, Friday or Sunday?                                                                                               Friday
Length: 570361, dtype: object

Chapter 10 Grouping with Functions

In [101]:
group_functions = df[["How old are you?"]]
group_functions

     How old are you?
0                  35
1                  41
2                  33
3                  31
4                  30
...               ...
5625               50
5626               43
5627               35
5628               38
5629               44

[5630 rows x 1 columns]

In [102]:
fun_group = df.groupby('How old are you?').mean()
fun_group

,"Fill in the blank: ""Taylor Swift is a force for ___________""",Please estimate the degrees of separation you have from the following folks [Bruce Lee],Please estimate the degrees of separation you have from the following folks [JK Rowling],Please estimate the degrees of separation you have from the following folks [Malala Yousafzai],Please estimate the degrees of separation you have from the following folks [Thom Yorke],Please estimate the degrees of separation you have from the following folks [JJ Abrams],Please estimate the degrees of separation you have from the following folks [Hillary Clinton],Please estimate the degrees of separation you have from the following folks [Donald Trump],Please estimate the degrees of separation you have from the following folks [Beyoncé Knowles]
How old are you?,,,,,,,,,
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
too old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
too old for this,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
very,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
x,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
７１＋,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Cross Tabs

In [103]:
pd.crosstab(data["Are you going actually going trick or treating yourself?"],data["Your gender:"], margins=True)

Your gender:,Female,I'd rather not say,Male,Other,All
Are you going actually going trick or treating yourself?,,,,,
No,365,25,707,16,1113
Yes,45,3,88,1,137
All,410,28,795,17,1250

Chapter 11 Generate date range

In [104]:
data = data.set_index(['Timestamp'])
print(data.loc['2016-10-28':'2016-10-30'])

                        Are you going actually going trick or treating yourself?  \
Timestamp
2016-10-28 04:15:30.366                                                 No
2016-10-28 05:35:13.854                                                 No
2016-10-28 07:00:27.176                                                 No
2016-10-28 08:10:58.506                                                 No
2016-10-28 08:54:54.924                                                 No
2016-10-28 09:01:00.049                                                 No
2016-10-28 09:03:52.617                                                 No
2016-10-28 09:07:58.826                                                 No
2016-10-28 09:10:29.100                                                 No
2016-10-28 09:10:38.669                                                 No
2016-10-28 09:51:59.394                                                 No
2016-10-28 10:12:14.405                                                 No
2016-10-28 10:19:10.361                                                 No
2016-10-28 10:32:54.679                                                 No
2016-10-28 10:54:41.121                                                 No
2016-10-28 12:41:25.987                                                 No
2016-10-28 12:59:36.013                                                 No
2016-10-28 13:08:58.202                                                 No
2016-10-28 13:16:27.652                                                 No
2016-10-28 13:42:50.055                                                 No
2016-10-28 14:26:09.078                                                 No
2016-10-28 14:37:24.766                                                 No
2016-10-28 15:58:09.398                                                Yes
2016-10-28 17:05:16.492                                                 No
2016-10-28 17:37:43.109                                                 No
2016-10-28 19:45:24.355                                                 No
2016-10-28 21:41:51.875                                                 No
2016-10-29 00:55:44.688                                                 No
2016-10-29 07:21:44.555                                                Yes
2016-10-29 10:53:26.543                                                 No
2016-10-29 11:56:55.930                                                 No
2016-10-29 12:02:52.773                                                Yes
2016-10-29 14:47:43.907                                                 No
2016-10-29 16:53:52.516                                                 No
2016-10-30 06:53:54.735                                                 No
2016-10-30 11:06:10.827                                                 No
2016-10-30 16:07:26.539                                                 No
2016-10-30 17:06:45.660                                                Yes

                        Your gender: How old are you?  \
Timestamp
2016-10-28 04:15:30.366       Female               38
2016-10-28 05:35:13.854         Male               46
2016-10-28 07:00:27.176       Female               29
2016-10-28 08:10:58.506         Male               34
2016-10-28 08:54:54.924         Male               39
2016-10-28 09:01:00.049         Male              NaN
2016-10-28 09:03:52.617       Female               24
2016-10-28 09:07:58.826       Female               38
2016-10-28 09:10:29.100         Male               31
2016-10-28 09:10:38.669         Male               51
2016-10-28 09:51:59.394        Other               33
2016-10-28 10:12:14.405       Female               25
2016-10-28 10:19:10.361       Female               29
2016-10-28 10:32:54.679       Female               26
2016-10-28 10:54:41.121       Female               44
2016-10-28 12:41:25.987         Male               24
2016-10-28 12:59:36.013       Female               31
2016-10-28 13:08:58.202       Female               71
2016-10-28 13:16:27.652       Female               32
2016-10-28 13:42:50.055         Male               27
2016-10-28 14:26:09.078       Female               26
2016-10-28 14:37:24.766         Male               46
2016-10-28 15:58:09.398         Male               45
2016-10-28 17:05:16.492       Female               45
2016-10-28 17:37:43.109       Female      49 11/12ths
2016-10-28 19:45:24.355         Male               31
2016-10-28 21:41:51.875       Female               31
2016-10-29 00:55:44.688         Male               27
2016-10-29 07:21:44.555       Female               47
2016-10-29 10:53:26.543         Male               35
2016-10-29 11:56:55.930       Female               34
2016-10-29 12:02:52.773       Female               56
2016-10-29 14:47:43.907         Male               54
2016-10-29 16:53:52.516       Female               52
2016-10-30 06:53:54.735         Male               33
2016-10-30 11:06:10.827         Male              NaN
2016-10-30 16:07:26.539         Male               48
2016-10-30 17:06:45.660       Female               44

                        Which country do you live in?  \
Timestamp
2016-10-28 04:15:30.366                          USA
2016-10-28 05:35:13.854                 United States
2016-10-28 07:00:27.176                           USA
2016-10-28 08:10:58.506                         Japan
2016-10-28 08:54:54.924                           USA
2016-10-28 09:01:00.049                           NaN
2016-10-28 09:03:52.617                           USA
2016-10-28 09:07:58.826                        Canada
2016-10-28 09:10:29.100                            US
2016-10-28 09:10:38.669                           USA
2016-10-28 09:51:59.394      United States of America
2016-10-28 10:12:14.405                           USA
2016-10-28 10:19:10.361                 United States
2016-10-28 10:32:54.679                            US
2016-10-28 10:54:41.121                        Canada
2016-10-28 12:41:25.987                 United States
2016-10-28 12:59:36.013                           USA
2016-10-28 13:08:58.202                           USA
2016-10-28 13:16:27.652                           USA
2016-10-28 13:42:50.055                           USA
2016-10-28 14:26:09.078                        Canada
2016-10-28 14:37:24.766                           USA
2016-10-28 15:58:09.398      united states of america
2016-10-28 17:05:16.492                 United States
2016-10-28 17:37:43.109                          U.S.
2016-10-28 19:45:24.355                        Canada
2016-10-28 21:41:51.875      United States of America
2016-10-29 00:55:44.688                 United States
2016-10-29 07:21:44.555                            US
2016-10-29 10:53:26.543                           USA
2016-10-29 11:56:55.930                  United State
2016-10-29 12:02:52.773                           USA
2016-10-29 14:47:43.907                           USA
2016-10-29 16:53:52.516                           USA
2016-10-30 06:53:54.735                 united states
2016-10-30 11:06:10.827                           NaN
2016-10-30 16:07:26.539                        canada
2016-10-30 17:06:45.660                            Us

                        Which state, province, county do you live in?  \
Timestamp
2016-10-28 04:15:30.366                                            MD
2016-10-28 05:35:13.854                                            ME
2016-10-28 07:00:27.176                                 Washington DC
2016-10-28 08:10:58.506                                         Kyoto
2016-10-28 08:54:54.924                                            NJ
2016-10-28 09:01:00.049                                           NaN
2016-10-28 09:03:52.617                                            CA
2016-10-28 09:07:58.826                                       Alberta
2016-10-28 09:10:29.100                                 Massachusetts
2016-10-28 09:10:38.669                                     Louisiana
2016-10-28 09:51:59.394                                            NC
2016-10-28 10:12:14.405                                            CA
2016-10-28 10:19:10.361                                    California
2016-10-28 10:32:54.679                                            DC
2016-10-28 10:54:41.121                                       Ontario
2016-10-28 12:41:25.987                                Massachusetts
2016-10-28 12:59:36.013                                            MO
2016-10-28 13:08:58.202                                            MD
2016-10-28 13:16:27.652                                      Virginia
2016-10-28 13:42:50.055                                            MI
2016-10-28 14:26:09.078                          Prince Edward Island
2016-10-28 14:37:24.766                                            IL
2016-10-28 15:58:09.398                                    Boo Jersey
2016-10-28 17:05:16.492                                 Pennsylvania
2016-10-28 17:37:43.109                                            IL
2016-10-28 19:45:24.355                                       Ontario
2016-10-28 21:41:51.875                                   Connecticut
2016-10-29 00:55:44.688                                    Washington
2016-10-29 07:21:44.555                                            WA
2016-10-29 10:53:26.543                                 Massachusetts
2016-10-29 11:56:55.930                                 New Hampshire
2016-10-29 12:02:52.773                                            NH
2016-10-29 14:47:43.907                                   wisconisin
2016-10-29 16:53:52.516                                            TX
2016-10-30 06:53:54.735                                     minnesota
2016-10-30 11:06:10.827                                           NaN
2016-10-30 16:07:26.539                                            BC
2016-10-30 17:06:45.660                                            Nh

                         [100 Grand Bar]  \
Timestamp
2016-10-28 04:15:30.366              JOY
2016-10-28 05:35:13.854              MEH
2016-10-28 07:00:27.176          DESPAIR
2016-10-28 08:10:58.506              MEH
2016-10-28 08:54:54.924          DESPAIR
2016-10-28 09:01:00.049              MEH
2016-10-28 09:03:52.617              MEH
2016-10-28 09:07:58.826              MEH
2016-10-28 09:10:29.100              JOY
2016-10-28 09:10:38.669              JOY
2016-10-28 09:51:59.394              JOY
2016-10-28 10:12:14.405          DESPAIR
2016-10-28 10:19:10.361              JOY
2016-10-28 10:32:54.679              MEH
2016-10-28 10:54:41.121              JOY
2016-10-28 12:41:25.987              MEH
2016-10-28 12:59:36.013              MEH
2016-10-28 13:08:58.202              JOY
2016-10-28 13:16:27.652              JOY
2016-10-28 13:42:50.055          DESPAIR
2016-10-28 14:26:09.078              MEH
2016-10-28 14:37:24.766              JOY
2016-10-28 15:58:09.398              JOY
2016-10-28 17:05:16.492              JOY
2016-10-28 17:37:43.109              MEH
2016-10-28 19:45:24.355              NaN
2016-10-28 21:41:51.875              JOY
2016-10-29 00:55:44.688              MEH
2016-10-29 07:21:44.555              MEH
2016-10-29 10:53:26.543              JOY
2016-10-29 11:56:55.930              JOY
2016-10-29 12:02:52.773              JOY
2016-10-29 14:47:43.907              MEH
2016-10-29 16:53:52.516              JOY
2016-10-30 06:53:54.735              JOY
2016-10-30 11:06:10.827              JOY
2016-10-30 16:07:26.539              NaN
2016-10-30 17:06:45.660              JOY

                         [Anonymous brown globs that come in black and orange wrappers]  \
Timestamp
2016-10-28 04:15:30.366                                                JOY
2016-10-28 05:35:13.854                                                MEH
2016-10-28 07:00:27.176                                            DESPAIR
2016-10-28 08:10:58.506                                                MEH
2016-10-28 08:54:54.924                                            DESPAIR
2016-10-28 09:01:00.049                                            DESPAIR
2016-10-28 09:03:52.617                                                MEH
2016-10-28 09:07:58.826                                            DESPAIR
2016-10-28 09:10:29.100                                                MEH
2016-10-28 09:10:38.669                                            DESPAIR
2016-10-28 09:51:59.394                                                MEH
2016-10-28 10:12:14.405                                                MEH
2016-10-28 10:19:10.361                                            DESPAIR
2016-10-28 10:32:54.679                                            DESPAIR
2016-10-28 10:54:41.121                                            DESPAIR
2016-10-28 12:41:25.987                                            DESPAIR
2016-10-28 12:59:36.013                                                MEH
2016-10-28 13:08:58.202                                            DESPAIR
2016-10-28 13:16:27.652                                            DESPAIR
2016-10-28 13:42:50.055                                                MEH
2016-10-28 14:26:09.078                                            DESPAIR
2016-10-28 14:37:24.766                                                MEH
2016-10-28 15:58:09.398                                            DESPAIR
2016-10-28 17:05:16.492                                                JOY
2016-10-28 17:37:43.109                                            DESPAIR
2016-10-28 19:45:24.355                                                MEH
2016-10-28 21:41:51.875                                            DESPAIR
2016-10-29 00:55:44.688                                            DESPAIR
2016-10-29 07:21:44.555                                            DESPAIR
2016-10-29 10:53:26.543                                            DESPAIR
2016-10-29 11:56:55.930                                                MEH
2016-10-29 12:02:52.773                                                MEH
2016-10-29 14:47:43.907                                                MEH
2016-10-29 16:53:52.516                                            DESPAIR
2016-10-30 06:53:54.735                                            DESPAIR
2016-10-30 11:06:10.827                                                MEH
2016-10-30 16:07:26.539                                            DESPAIR
2016-10-30 17:06:45.660                                                MEH

                         [Any full-sized candy bar]  [Black Jacks]  \
Timestamp
2016-10-28 04:15:30.366                         MEH            NaN
2016-10-28 05:35:13.854                         JOY            MEH
2016-10-28 07:00:27.176                         JOY        DESPAIR
2016-10-28 08:10:58.506                         JOY            MEH
2016-10-28 08:54:54.924                         JOY        DESPAIR
2016-10-28 09:01:00.049                         JOY            MEH
2016-10-28 09:03:52.617                         MEH            MEH
2016-10-28 09:07:58.826                         JOY            MEH
2016-10-28 09:10:29.100                         JOY            JOY
2016-10-28 09:10:38.669                         JOY        DESPAIR
2016-10-28 09:51:59.394                         JOY            NaN
2016-10-28 10:12:14.405                         MEH        DESPAIR
2016-10-28 10:19:10.361                         JOY        DESPAIR
2016-10-28 10:32:54.679                         MEH            MEH
2016-10-28 10:54:41.121                         JOY            NaN
2016-10-28 12:41:25.987                         JOY            MEH
2016-10-28 12:59:36.013                         JOY        DESPAIR
2016-10-28 13:08:58.202                         MEH        DESPAIR
2016-10-28 13:16:27.652                         JOY            MEH
2016-10-28 13:42:50.055                         JOY            MEH
2016-10-28 14:26:09.078                         JOY            MEH
2016-10-28 14:37:24.766                         JOY            JOY
2016-10-28 15:58:09.398                         JOY            MEH
2016-10-28 17:05:16.492                         JOY        DESPAIR
2016-10-28 17:37:43.109                         JOY        DESPAIR
2016-10-28 19:45:24.355                         JOY            NaN
2016-10-28 21:41:51.875                         JOY        DESPAIR
2016-10-29 00:55:44.688                         JOY            MEH
2016-10-29 07:21:44.555                         NaN            JOY
2016-10-29 10:53:26.543                         JOY            MEH
2016-10-29 11:56:55.930                         JOY            MEH
2016-10-29 12:02:52.773                         JOY            MEH
2016-10-29 14:47:43.907                         NaN        DESPAIR
2016-10-29 16:53:52.516                         JOY            MEH
2016-10-30 06:53:54.735                         JOY        DESPAIR
2016-10-30 11:06:10.827                         JOY            NaN
2016-10-30 16:07:26.539                         JOY        DESPAIR
2016-10-30 17:06:45.660                         JOY            JOY

                         [Bonkers (the candy)]  ...  \
Timestamp                                       ...
2016-10-28 04:15:30.366                    NaN  ...
2016-10-28 05:35:13.854                    MEH  ...
2016-10-28 07:00:27.176                DESPAIR  ...
2016-10-28 08:10:58.506                    MEH  ...
2016-10-28 08:54:54.924                    MEH  ...
2016-10-28 09:01:00.049                DESPAIR  ...
2016-10-28 09:03:52.617                    MEH  ...
2016-10-28 09:07:58.826                    MEH  ...
2016-10-28 09:10:29.100                    MEH  ...
2016-10-28 09:10:38.669                    MEH  ...
2016-10-28 09:51:59.394                    NaN  ...
2016-10-28 10:12:14.405                DESPAIR  ...
2016-10-28 10:19:10.361                    MEH  ...
2016-10-28 10:32:54.679                    MEH  ...
2016-10-28 10:54:41.121                    MEH  ...
2016-10-28 12:41:25.987                DESPAIR  ...
2016-10-28 12:59:36.013                DESPAIR  ...
2016-10-28 13:08:58.202                    NaN  ...
2016-10-28 13:16:27.652                    MEH  ...
2016-10-28 13:42:50.055                    MEH  ...
2016-10-28 14:26:09.078                    MEH  ...
2016-10-28 14:37:24.766                DESPAIR  ...
2016-10-28 15:58:09.398                    MEH  ...
2016-10-28 17:05:16.492                    MEH  ...
2016-10-28 17:37:43.109                DESPAIR  ...
2016-10-28 19:45:24.355                    NaN  ...
2016-10-28 21:41:51.875                DESPAIR  ...
2016-10-29 00:55:44.688                    NaN  ...
2016-10-29 07:21:44.555                DESPAIR  ...
2016-10-29 10:53:26.543                    MEH  ...
2016-10-29 11:56:55.930                    MEH  ...
2016-10-29 12:02:52.773                    MEH  ...
2016-10-29 14:47:43.907                DESPAIR  ...
2016-10-29 16:53:52.516                    MEH  ...
2016-10-30 06:53:54.735                    MEH  ...
2016-10-30 11:06:10.827                DESPAIR  ...
2016-10-30 16:07:26.539                    MEH  ...
2016-10-30 17:06:45.660                    MEH  ...

                        Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling]  \
Timestamp
2016-10-28 04:15:30.366                                        3 or higher
2016-10-28 05:35:13.854                                                  2
2016-10-28 07:00:27.176                                        3 or higher
2016-10-28 08:10:58.506                                        3 or higher
2016-10-28 08:54:54.924                                        3 or higher
2016-10-28 09:01:00.049                                                  1
2016-10-28 09:03:52.617                                        3 or higher
2016-10-28 09:07:58.826                                        3 or higher

In [107]:
Timestamp = df['Timestamp']

0      2015-10-23 08:46:20.451
1      2015-10-23 08:46:51.583
2      2015-10-23 08:47:34.285
3      2015-10-23 08:47:58.964
4      2015-10-23 08:48:11.719
                 ...
5625   2015-10-31 05:23:40.526
5626   2015-10-31 05:29:26.937
5627   2015-10-31 06:13:29.083
5628   2015-10-31 06:26:52.566
5629   2015-10-31 06:41:31.904
Name: Timestamp, Length: 5630, dtype: datetime64[ns]

In [54]:
index = pd.date_range('2016-10-24','2016-10-25')
index

DatetimeIndex(['2016-10-24', '2016-10-25'], dtype='datetime64[ns]', freq='D')

In [109]:
str(Timestamp)

'0      2015-10-23 08:46:20.451\n1      2015-10-23 08:46:51.583\n2      2015-10-23 08:47:34.285\n3      2015-10-23 08:47:58.964\n4      2015-10-23 08:48:11.719\n                 ...          \n5625   2015-10-31 05:23:40.526\n5626   2015-10-31 05:29:26.937\n5627   2015-10-31 06:13:29.083\n5628   2015-10-31 06:26:52.566\n5629   2015-10-31 06:41:31.904\nName: Timestamp, Length: 5630, dtype: datetime64[ns]'